### PR TITLE
Issues #5 and #21 fixed

### PR DESCRIPTION
**Pull request by marcoplebani85**
Issue #5 fixed, "trajectory summary" (summarize median as well as mean). Added a switch option to the function to summarise with median or mean, with median as the default.

Issue #21 fixed (”Improve summarize_trajectories function to keep information about treatments”).
The fix was done on merge_data(), so summarize_trajectories() did not change.

NOTE: we need to add to the BEMOVI user manual a list of no-no variable names that must not be used in video.description.file. In particular, "id" is reserved for particle ID whithin BEMOVI, hence there cannot be a video.description.file$id column. It's worth mentioning because many would use "id" for "treatment id", or "microcosm id", etc (I would).

### CODE REVIEW

**Comment by pennekampster** [comment]
Hi Marco, thanks for your contribution! I have a question regarding keeping information about treatments: you say you added the video description file in the merge_data function, but the video information was merged there anyway, whereas it is discarded in the summarize_trajectories function, which apparently you did not change. So I am not sure issue 21 is really resolved. Could you make a new pull request with just the changes to the summary trajectory function?

**Comment by marcoplebani85** [comment]
Sure, I’ll look into it. I will do it on wednesday next week if it’s not too late.

Tschüss!

Marco

**Comment by marcoplebani85** [comment]
Hi Frank, I fixed the issue I believe.

**Comment by pennekampster** [comment]
Dear Marco,

thanks for your contribution. I'll merge the pull request and do some testing on the updated function! When ready, it will be shipped with the first BEMOVI release!

Many thanks,

   Frank

**Pull request merged**
